// Auto-generated by scripts/config_key_sync.py — DO NOT EDIT
// Source: config/touch_pipeline_config.yaml

#include "TouchPipelineConfigKeys.h"
#include "SolverBuildConfig.h"

#if EGOTOUCH_CONFIG_ENABLED

#include "TouchPipeline.h"
#include "ConfigParse.h"

#include <ostream>

namespace Solvers {
namespace TouchConfig {

// ── GetConfigSchema ──
std::vector<ConfigParam> GetConfigSchema(TouchPipelineMembers& m) {
    std::vector<ConfigParam> s;
    s.reserve(7);

    // ── Signal Conditioning ──
    s.emplace_back(kBaselineBackgroundAlphaShiftName, "Baseline Background Alpha Shift", ConfigParam::Int, const_cast<int*>(&m.baseline->m_backgroundAlphaShift), 0, 15).Module("Signal Conditioning");
    s.emplace_back(kBaselineBackgroundMaxStepName, "Baseline Background Max Step", ConfigParam::Int, const_cast<int*>(&m.baseline->m_backgroundMaxStep), 1, 2048).Module("Signal Conditioning");
    s.emplace_back(kBaselineNoFingerAlphaShiftName, "Baseline No-Finger Alpha Shift", ConfigParam::Int, const_cast<int*>(&m.baseline->m_noFingerAlphaShift), 0, 15).Module("Signal Conditioning");
    s.emplace_back(kBaselineNoFingerMaxStepName, "Baseline No-Finger Max Step", ConfigParam::Int, const_cast<int*>(&m.baseline->m_noFingerMaxStep), 1, 2048).Module("Signal Conditioning");
    s.emplace_back(kBaselineRecoveryAlphaShiftName, "Baseline Recovery Alpha Shift", ConfigParam::Int, const_cast<int*>(&m.baseline->m_recoveryAlphaShift), 0, 15).Module("Signal Conditioning");
    s.emplace_back(kBaselineRecoveryMaxFramesName, "Baseline Recovery Max Frames", ConfigParam::Int, const_cast<int*>(&m.baseline->m_recoveryMaxFrames), 1, 120).Module("Signal Conditioning");
    s.emplace_back(kBaselineRecoveryMaxStepName, "Baseline Recovery Max Step", ConfigParam::Int, const_cast<int*>(&m.baseline->m_recoveryMaxStep), 1, 2048).Module("Signal Conditioning");

    return s;
}

// ── SaveConfig ──
void SaveConfig(const TouchPipelineMembers& m, std::ostream& out) {
    out << kBaselineBackgroundAlphaShiftName << "=" << m.baseline->m_backgroundAlphaShift << "\n";
    out << kBaselineBackgroundMaxStepName << "=" << m.baseline->m_backgroundMaxStep << "\n";
    out << kBaselineNoFingerAlphaShiftName << "=" << m.baseline->m_noFingerAlphaShift << "\n";
    out << kBaselineNoFingerMaxStepName << "=" << m.baseline->m_noFingerMaxStep << "\n";
    out << kBaselineRecoveryAlphaShiftName << "=" << m.baseline->m_recoveryAlphaShift << "\n";
    out << kBaselineRecoveryMaxFramesName << "=" << m.baseline->m_recoveryMaxFrames << "\n";
    out << kBaselineRecoveryMaxStepName << "=" << m.baseline->m_recoveryMaxStep << "\n";
}

// ── LoadConfig ──
void LoadConfig(TouchPipelineMembers& m, const std::string& key, const std::string& value) {
    try {
        if (key == kBaselineBackgroundAlphaShiftName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 15) v = 15;
            m.baseline->m_backgroundAlphaShift = v;
        }
        else if (key == kBaselineBackgroundMaxStepName) {
            int v = ParseConfigInt(key, value);
            if (v < 1) v = 1;
            if (v > 2048) v = 2048;
            m.baseline->m_backgroundMaxStep = v;
        }
        else if (key == kBaselineNoFingerAlphaShiftName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 15) v = 15;
            m.baseline->m_noFingerAlphaShift = v;
        }
        else if (key == kBaselineNoFingerMaxStepName) {
            int v = ParseConfigInt(key, value);
            if (v < 1) v = 1;
            if (v > 2048) v = 2048;
            m.baseline->m_noFingerMaxStep = v;
        }
        else if (key == kBaselineRecoveryAlphaShiftName) {
            int v = ParseConfigInt(key, value);
            if (v < 0) v = 0;
            if (v > 15) v = 15;
            m.baseline->m_recoveryAlphaShift = v;
        }
        else if (key == kBaselineRecoveryMaxFramesName) {
            int v = ParseConfigInt(key, value);
            if (v < 1) v = 1;
            if (v > 120) v = 120;
            m.baseline->m_recoveryMaxFrames = v;
        }
        else if (key == kBaselineRecoveryMaxStepName) {
            int v = ParseConfigInt(key, value);
            if (v < 1) v = 1;
            if (v > 2048) v = 2048;
            m.baseline->m_recoveryMaxStep = v;
        }
    } catch (const ConfigParseError& error) {
        LogConfigParseWarning("TouchPipeline", __func__, key, value, error);
    }
}

}  // namespace TouchConfig
}  // namespace Solvers

#endif  // EGOTOUCH_CONFIG_ENABLED
