if(NOT DEFINED SERVICE_EXE OR NOT EXISTS "${SERVICE_EXE}")
    message(FATAL_ERROR "SERVICE_EXE does not exist: ${SERVICE_EXE}")
endif()

if(NOT DEFINED APP_EXE OR NOT EXISTS "${APP_EXE}")
    message(FATAL_ERROR "APP_EXE does not exist: ${APP_EXE}")
endif()

if(NOT DEFINED SOURCE_DEFAULT_CONFIG OR NOT EXISTS "${SOURCE_DEFAULT_CONFIG}")
    message(FATAL_ERROR "SOURCE_DEFAULT_CONFIG does not exist: ${SOURCE_DEFAULT_CONFIG}")
endif()

file(SHA256 "${SOURCE_DEFAULT_CONFIG}" source_hash)

function(verify_file_hash label file_path)
    if(NOT EXISTS "${file_path}")
        message(FATAL_ERROR "${label} does not exist: ${file_path}")
    endif()

    file(SHA256 "${file_path}" file_hash)
    if(NOT source_hash STREQUAL file_hash)
        message(FATAL_ERROR "${label} differs from repository config/default.yaml: ${file_path}")
    endif()
endfunction()

function(verify_target_config target_name exe_path)
    get_filename_component(target_dir "${exe_path}" DIRECTORY)
    set(output_default "${target_dir}/config/default.yaml")
    verify_file_hash("${target_name} output config/default.yaml" "${output_default}")
endfunction()

verify_target_config("EGoTouchService" "${SERVICE_EXE}")
verify_target_config("EGoTouchApp" "${APP_EXE}")

function(expand_wix_source out_var source_attr wix_file)
    if(source_attr MATCHES "^\\$\\(var\\.BuildOutputDir\\)(.*)$")
        if(NOT DEFINED WIX_BUILD_OUTPUT_DIR)
            message(FATAL_ERROR "WIX_BUILD_OUTPUT_DIR is required to expand ${source_attr}")
        endif()
        set(suffix "${CMAKE_MATCH_1}")
        string(REPLACE "\\" "/" suffix "${suffix}")
        string(REGEX REPLACE "^/+" "" suffix "${suffix}")
        set(expanded "${WIX_BUILD_OUTPUT_DIR}/${suffix}")
    else()
        file(TO_CMAKE_PATH "${source_attr}" source_path)
        if(IS_ABSOLUTE "${source_path}")
            set(expanded "${source_path}")
        else()
            if(DEFINED WIX_SOURCE_BASE_DIR)
                set(expanded "${WIX_SOURCE_BASE_DIR}/${source_path}")
            else()
                get_filename_component(wix_dir "${wix_file}" DIRECTORY)
                set(expanded "${wix_dir}/${source_path}")
            endif()
        endif()
    endif()
    file(TO_CMAKE_PATH "${expanded}" expanded)
    set(${out_var} "${expanded}" PARENT_SCOPE)
endfunction()

function(verify_wix_default_config wix_name wix_path)
    if(NOT EXISTS "${wix_path}")
        message(FATAL_ERROR "${wix_name} does not exist: ${wix_path}")
    endif()

    file(READ "${wix_path}" wix_text)
    string(REGEX MATCH "<File[^>]*Id=\"DefaultConfigYAML\"[^>]*Source=\"([^\"]+)\"" default_config_match "${wix_text}")
    if(NOT default_config_match)
        message(FATAL_ERROR "${wix_name} does not define File Id=\"DefaultConfigYAML\" with a Source attribute")
    endif()

    set(source_attr "${CMAKE_MATCH_1}")
    expand_wix_source(expanded_source "${source_attr}" "${wix_path}")
    verify_file_hash("${wix_name} DefaultConfigYAML source" "${expanded_source}")
endfunction()

if(DEFINED BUILD_DIR AND DEFINED INSTALL_PREFIX)
    if("${BUILD_DIR}" STREQUAL "")
        message(FATAL_ERROR "BUILD_DIR must not be empty")
    endif()
    if("${INSTALL_PREFIX}" STREQUAL "")
        message(FATAL_ERROR "INSTALL_PREFIX must not be empty")
    endif()
    file(REMOVE_RECURSE "${INSTALL_PREFIX}")
    execute_process(
        COMMAND "${CMAKE_COMMAND}" --install "${BUILD_DIR}" --prefix "${INSTALL_PREFIX}"
        RESULT_VARIABLE install_result
        OUTPUT_VARIABLE install_stdout
        ERROR_VARIABLE install_stderr
    )
    if(NOT install_result EQUAL 0)
        message(FATAL_ERROR "cmake --install failed (${install_result})\n${install_stdout}\n${install_stderr}")
    endif()

    if(NOT EXISTS "${INSTALL_PREFIX}/EGoTouchService.exe")
        message(FATAL_ERROR "install prefix is missing EGoTouchService.exe: ${INSTALL_PREFIX}/EGoTouchService.exe")
    endif()
    if(NOT EXISTS "${INSTALL_PREFIX}/EGoTouchApp.exe")
        message(FATAL_ERROR "install prefix is missing EGoTouchApp.exe: ${INSTALL_PREFIX}/EGoTouchApp.exe")
    endif()
    verify_file_hash("installed config/default.yaml" "${INSTALL_PREFIX}/config/default.yaml")
endif()

if(DEFINED WIX_SETUP)
    verify_wix_default_config("EGoTouchSetup.wxs" "${WIX_SETUP}")
endif()

if(DEFINED WIX_TEST_SETUP)
    verify_wix_default_config("EGoTouchTestSetup.wxs" "${WIX_TEST_SETUP}")
endif()
